# Lista Blanca de Dominios - NEXUS CORE v3.0
# Gubernamentales
WHITE_LIST=("sat.gob.mx" "banxico.org.mx" "gob.mx")

# Educación y Certificación (PEN-200)
WHITE_LIST+=("offsec.com" "portal.offsec.com" "tryhackme.com" "hackthebox.com")

# Repositorios de Código
WHITE_LIST+=("github.com" "raw.githubusercontent.com")
